### ISSUE TITLE
Window for the regular app does not follow the title bar 

### ISSUE THREAD

**Issue by Cateatacat** [ScratchFakemon/Firefly#1] opened 2024-08-31 23:57 UTC
I tried the regular app and I saw that the window doesn't follow the title bar

**Comment by ScratchFakemon** [comment] 2024-09-01 15:59
OK

**Comment by ScratchFakemon** [comment] 2024-09-01 17:24
I tested it, and I don't see your issue. Your computer might be 
### l a g g i n g 
or something

**Comment by webbrowser11** [comment] 2024-09-01 20:28
he means its not always at the same position as the title bar. it wiggles around.

**Comment by webbrowser11** [comment] 2024-09-01 20:28
neither does the exit thing if you look closely.

**Comment by webbrowser11** [comment] 2024-09-01 20:31
or who knows maybe ITS NOT A BUG ITS A FEATURE!

**Comment by ScratchFakemon** [comment] 2024-09-01 23:21
it's not my fault, it's a problem with the Clones+ extension.

**Comment by webbrowser11** [comment] 2024-09-01 23:30
oh

**Comment by webbrowser11** [comment] 2024-09-01 23:30
u should close this then

**Closed** 2024-09-02 00:52 UTC
